import QueryProvider from './Query/queryProvider'
import { Providers } from './Redux/reduxProvider'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'RNJ Silver Stock',
  description: 'Generated by create next app',
}


export default function RootLayout({ products, children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="bg-slate-900 text-white min-h-screen">
          <Providers>
            <QueryProvider>
              <Navbar />
              {children}
            </QueryProvider>
          </Providers>
        </section>
      </body>
    </html>
  )
}

